sudo: required
services:
  - docker
language: go
go:
  - 1.10.4
install:
  - go get -u github.com/vbatts/git-validation
script:
  - git-validation -run DCO,short-subject
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - make docker-proto
  - git diff $(find . -name "*.pb.*go" -o -name "api.swagger.json" | grep -v vendor) | wc -l | grep "^0"
  - ./hack/check-api-version.sh
  - make sdk-check-version
  - make install
  - make vet
  - bash hack/docker-integration-test.sh
  - make docker-test
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin;
      make push-mock-sdk-server;
    fi
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - eng@portworx.com
    on_success: change
    on_failure: always
