FROM alpine
MAINTAINER luis@portworx.com

EXPOSE 9100 9110
ADD ./etc/config/config.yaml /config.yaml
ADD ./bin/osd /
RUN apk update && apk add xfsprogs e2fsprogs btrfs-progs
ENTRYPOINT ["/osd"]
CMD ["-d", "-f", "/config.yaml"]
